# Generated by Django 5.0.3 on 2024-03-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('fulltime', 'Full-Time'), ('parttime', 'Part-Time'), ('contract', 'Contract')], max_length=20)),
                ('benefits', models.TextField()),
                ('event_location', models.CharField(max_length=255)),
                ('required_skills', models.TextField()),
                ('registration_amount', models.CharField(max_length=255)),
            ],
        ),
    ]
