# Generated by Django 5.0.3 on 2024-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager_module', '0002_alter_eventdetails_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='benefits',
            field=models.TextField(blank=True, default='Your Default Value', null=True),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='registration_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
