# Generated by Django 5.0.3 on 2024-03-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventParticipant_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='university',
            field=models.CharField(max_length=100),
        ),
    ]
