# Generated by Django 5.0.3 on 2024-03-07 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager_module', '0003_alter_eventdetails_benefits_and_more'),
        ('EventParticipant_module', '0002_alter_applicant_email_alter_applicant_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField(max_length=100)),
                ('event_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventManager_module.eventdetails')),
            ],
        ),
    ]
